## 데이터프레임->시리즈->리스트로 변환 tolist()

In [1]:
import pandas as pd

df= pd.read_csv('경기_행복주택현황.csv', encoding='cp949',index_col = 1)
df

,사업지구명,공급세대수,준공일자,유형,데이터기준일자
위치정보,,,,,
경기도 화성동탄 2 신도시 내 A76-1BL(산척동 750),동탄 호수공원,995,2020-10-16,신혼부부,2022-03-03
경기도 화성시 진안동 524-3,화성 진안1,16,2017-12-21,청년,2022-03-03
경기도 화성시 진안동 882-1,화성 진안2,15,2018-02-28,청년,2022-03-03
경기도 평택시 포승황해경제자유구역 내 평택BIX A-2,평택 BIX,330,2021-04-30,산업단지형,2022-03-03
경기도 평택시 고덕국제화계획지구 A-62블럭,고덕 서정리역,800,NaN,신혼부부,2022-03-03
경기도 연천군 통현리 812번지(연천BIX 주거1),연천 BIX,100,NaN,산업단지형,2022-03-03
경기도 남양주시 다산동 6027,다산역A2,970,2019-09-02,신혼부부,2022-03-03
경기도 남양주시 다산신도시 지금A5 BL,다산지금 A5,2078,NaN,신혼부부,2022-03-03
경기도 가평군 가평읍 읍내리 608-5,가평청사복합,42,2019-06-17,청년,2022-03-03
경기도 광주역세권 도시개발사업지구 A2BL(역동 169-11일원),경기 광주역,500,NaN,신혼부부,2022-03-03
경기도 양평군 양평읍 공흥리 441-22,양평 공흥,40,2019-01-28,청년,2022-03-03
"경기도 양평군 창대리 701, 700-3",양평 남한강,49,NaN,신혼부부,2022-03-03
경기도 의왕시 삼동 160-27번지(부곡시장1길 42),의왕역,50,2020-01-22,청년,2022-03-03
경기도 수원시 영통구 이의동 1284,수원 광교,204,2018-04-26,신혼부부,2022-03-03
경기도 수원시 망포동 769,수원 영통,100,2019-06-07,청년,2022-03-03
경기도 수원시 영통구 원천동 559번지(광교 도시8블록),광교 원천,300,2020-10-27,청년,2022-03-03
"경기도 용인시 수지구 죽전동 494-5, 24번지",용인 죽전,85,NaN,청년,2022-03-03
경기도 오산시 가장동 375-3번지,오산 가장,50,2020-02-04,산업단지형,2022-03-03
경기도 안성시 당왕동 455번지 등 5필지,안성 청사복합,300,NaN,청년,2022-03-03
경기도 성남시 금토동 판교제2테크노밸리 G4-1,판교2밸리,300,NaN,산업단지형,2022-03-03
경기도 용인시 기흥구 영덕동 751-3번지,용인영덕,106,NaN,청년,2022-03-03
경기도 안양시 관양동 523-4번지 (안양관양고 도시개발사업지구),안양관양2,300,NaN,신혼부부,2022-03-03
경기도 평택시 팽성읍 안정리 3-8번지 일원,평택안정,250,NaN,청년,2022-03-03
경기도 광주시 역동 광주역세권 개발지구 內,광주역세권,393,NaN,청년,2022-03-03
경기도 파주시 금촌동 799-4,파주병원복합,50,2019-08-22,실버형,2022-03-03
경기도 하남시 덕풍동 828,하남 덕풍,131,NaN,신혼부부,2022-03-03
경기도 성남시 분당구 삼평동 700,성남 판교,300,2020-08-10,산업단지형,2022-03-03
경기도 안양시 동안구 관양동 1498-21 일원,안양 관양,56,2018-03-26,신혼부부,2022-03-03
경기도 안산시 원시동 782번지,안산 스마트허브,232,2021-04-30,산업단지형,2022-03-03
경기도 성남시 중원구 하대원동 121-5,성남하대원,14,2019-06-26,청년,2022-03-03
경기도 화성시 동탄2 신도시 택지개발지구 내 A105BL,동탄2 A105,1500,NaN,청년,2022-03-03

In [2]:
import pandas as pd

df= pd.read_csv('경기_행복주택현황.csv', encoding='cp949')
df2 = df['유형']
df2

0      신혼부부
1        청년
2        청년
3     산업단지형
4      신혼부부
5     산업단지형
6      신혼부부
7      신혼부부
8        청년
9      신혼부부
10       청년
11     신혼부부
12       청년
13     신혼부부
14       청년
15       청년
16       청년
17    산업단지형
18       청년
19    산업단지형
20       청년
21     신혼부부
22       청년
23       청년
24      실버형
25     신혼부부
26    산업단지형
27     신혼부부
28    산업단지형
29       청년
30       청년
Name: 유형, dtype: object

In [3]:
import pandas as pd

df= pd.read_csv('경기_행복주택현황.csv', encoding='cp949')
df2 = df['유형']
type(df2)

pandas.core.series.Series

In [4]:
import pandas as pd

df= pd.read_csv('경기_행복주택현황.csv', encoding='cp949')
df2 = df['유형'].tolist()
type(df2)

list

In [5]:
import pandas as pd
import numpy as np
df= pd.read_csv('경기_행복주택현황.csv', encoding='cp949',index_col = 1)

dic_list = df['유형'].tolist()
print(dic_list)

['신혼부부', '청년', '청년', '산업단지형', '신혼부부', '산업단지형', '신혼부부', '신혼부부', '청년', '신혼부부', '청년', '신혼부부', '청년', '신혼부부', '청년', '청년', '청년', '산업단지형', '청년', '산업단지형', '청년', '신혼부부', '청년', '청년', '실버형', '신혼부부', '산업단지형', '신혼부부', '산업단지형', '청년', '청년']